export { default as Sidebar } from './dashboard/Sidebar.vue'
export { default as ServerStatus } from './dashboard/ServerStatus.vue'

export { default as LaunchScene } from './tabs/accounts/LaunchScene.vue'
export { default as AuthTabsWidget } from './tabs/accounts/AuthTabsWidget.vue'

export { default as AuthForm } from './tabs/login/AuthForm.vue'
export { default as StepProgress } from './tabs/login/StepProgress.vue'

export { default as AddProfileTab } from './tabs/AddProfileTab.vue'
export { default as OfflineProfileForm } from './tabs/profile/OfflineProfileForm.vue'
export { default as DebugTab } from './tabs/DebugTab.vue'

export { default as PathPicker } from './tabs/settings/PathPicker.vue'
export { default as LauncherUpdate } from './tabs/settings/LauncherUpdate.vue'
export { default as LauncherBehavior } from './tabs/settings/LauncherBehavior.vue'
export { default as ConfigCleanup } from './tabs/settings/ConfigCleanup.vue'
export { default as ProjectDelete } from './tabs/settings/ProjectDelete.vue'
export { default as ThemeSelector } from './tabs/settings/ThemeSelector.vue'
export { default as SettingsInfoRow } from './tabs/settings/SettingsInfoRow.vue'
export { default as JvmPreset } from './tabs/settings/JvmPreset.vue'
export { default as AlternativeJavaButton } from './tabs/settings/AlternativeJavaButton.vue'
export { default as MemorySlider } from './tabs/settings/MemorySlider.vue'
export { default as ServerConnect } from './tabs/settings/ServerConnect.vue'
export { default as IntegrityCheck } from './tabs/settings/IntegrityCheck.vue'
export { default as SkinSettings } from './tabs/settings/SkinSettings.vue'
export { default as ModrinthTab } from './tabs/ModrinthTab.vue'
export { default as CpmSettings } from './tabs/settings/CpmSettings.vue'
export { default as AccountSettings } from './tabs/settings/AccountSettings.vue'
export { default as GameSettings } from './tabs/settings/GameSettings.vue'
export { default as SettingsSection } from './tabs/settings/SettingsSection.vue'
export { default as SettingsSaveBar } from './tabs/settings/SettingsSaveBar.vue'

export type { TabItem, TabKey } from './types'
