// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDir():Promise<string>;

export function GetFile(arg1:string,arg2:string):Promise<string>;

export function GetFileInfo(arg1:string):Promise<string>;

export function GetFileList():Promise<string>;

export function StartJvm():Promise<void>;
