// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDir() {
  return window['go']['main']['App']['CheckDir']();
}

export function GetFile(arg1) {
  return window['go']['main']['App']['GetFile'](arg1);
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetFileList() {
  return window['go']['main']['App']['GetFileList']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
